/-!
# v9 Lean Appendix

Extends `Inventory` (new external axioms) and adds `RobustTrustV9` namespace with
the v9 Pareto-frontier primitives and the full 28-theorem surface as `sorry` stubs.

Per the v9 decomposition (lean/decomposition.md, generated by Extended Pro on
2026-05-21, chat 6a0f9a2b). See §13 of that document for self-flagged risks
that the upcoming reviewer pass will adjudicate.

Conventions:
- All declarations within `RobustTrustV9` open `RobustTrustV8` for primitive reuse.
- Inventory v9 axioms use `axiom` and `opaque` (not deprecated `constant`).
- Theorem names with hyphens are written as French-quoted identifiers
  (e.g. `«binary-L_B5-endpoint-stationarity-total-balance»`).
- Many structure fields are abstract `Prop` placeholders to be refined per-lemma
  by downstream prover sessions; the skeleton compiles with all goals `sorry`.
-/

namespace Inventory

open MeasureTheory ProbabilityTheory

/-! ## New v9 Inventory axioms (added 2026-05-21) -/

/-- Abstract Clarke subdifferential placeholder (Clarke 1990 §2.5). -/
opaque ClarkeSubdiff
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] :
    (E → ℝ) → E → Set E

/-- Abstract Clarke normal cone placeholder (Clarke 1990 §2.4). -/
opaque ClarkeNormalCone
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] :
    Set E → E → Set E

structure ClarkeDanskinHyp
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (_F : E → ℝ) (_x : E) (_Candidates : Set E) where
  locallyLipschitz : Prop
  compactActiveSet : Prop
  danskinRepresentation : Prop

/-- **Clarke–Danskin stationarity.** Clarke subdifferential of an integral /
Danskin's theorem applied to a value functional. Source: Clarke 1990, *Optimization
and Nonsmooth Analysis*, §2.7; Danskin envelope theorem. -/
axiom clarke_danskin_stationarity
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (F : E → ℝ) (x : E) (Candidates : Set E)
    (h : ClarkeDanskinHyp F x Candidates) :
    ∃ ξ ∈ Candidates, ξ ∈ ClarkeSubdiff F x

/-- **Clarke–Fermat normal-cone stationarity.** Clarke subdifferential at a local
extremum is contained in the normal cone. Source: Clarke 1990, Fermat rule for
locally Lipschitz functions constrained to a closed set. -/
axiom clarke_fermat_normal_cone
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (F : E → ℝ) (C : Set E) (x : E)
    (_hx : x ∈ C)
    (_hLocalMax : Prop)
    (ξ : E)
    (_hξ : ξ ∈ ClarkeSubdiff F x) :
    -ξ ∈ ClarkeNormalCone C x

structure StrassenMarginalDominance
    {α β : Type*} [MeasurableSpace α] [MeasurableSpace β]
    (_μ : Measure α) (_ν : Measure β) (_R : Set (α × β)) where
  dualInequality : Prop

/-- **Strassen marginals theorem (1965).** Coupling existence under marginal
dominance / Kantorovich–Rubinstein duality form. Source: Strassen 1965,
*The existence of probability measures with given marginals*, Ann. Math. Stat. -/
axiom strassen_marginals
    {α β : Type*} [MeasurableSpace α] [MeasurableSpace β]
    (μ : Measure α) (ν : Measure β) (R : Set (α × β))
    (_h : StrassenMarginalDominance μ ν R) :
    ∃ π : Measure (α × β),
      (Measure.map Prod.fst π = μ) ∧
      (Measure.map Prod.snd π = ν) ∧
      π Rᶜ = 0

structure ConicFarkasInstance : Type where
  primalFeasible : Prop
  dualNonpositive : Prop

/-- **Farkas / strong conic LP duality.** Used for finite cone-Hall (G1) and
the polyhedral LP threshold (G4). Source: Farkas lemma; finite-dimensional
conic strong duality (Boyd–Vandenberghe §5). -/
axiom farkas_lp_duality_conic
    (inst : ConicFarkasInstance) :
    inst.primalFeasible ↔ inst.dualNonpositive

structure BergeMaximumHyp
    {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
    (_F : X → Set Y) (_f : X → Y → ℝ) where
  compactValues : Prop
  closedGraph : Prop
  continuousObjective : Prop

/-- **Berge maximum theorem (set-valued).** Audit task: many uses may be
dischargeable from Mathlib's existing compactness/continuity. Source:
Aliprantis–Border §17. -/
axiom berge_maximum_set_valued
    {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
    (_F : X → Set Y) (_f : X → Y → ℝ)
    (_h : BergeMaximumHyp _F _f) :
    Prop

/-- **Hausdorff–Alexandroff continuous surjection.** Every nonempty compact
metric space is a continuous image of the Cantor space. Source: Kechris 1995,
*Classical Descriptive Set Theory*, Thm 4.18; or any standard descriptive
set theory text. -/
axiom hausdorff_alexandroff_continuous_surjection
    (K : Type*) [TopologicalSpace K] [CompactSpace K] [T2Space K]
    [SecondCountableTopology K] :
    Prop  -- placeholder until CantorSpace is fixed in Mathlib

end Inventory

namespace RobustTrustV9

open RobustTrustV8 MeasureTheory
open scoped BigOperators

noncomputable section

/-! ## §2 New v9 primitives -/

variable (model : RobustTrustModel)

/-- A profile `w` is on the weak Pareto frontier of the feasible payoff set
`PayoffProfileSet model` if no other feasible profile strictly dominates it
coordinate-wise. -/
def WeakParetoProfile (w : Profile model) : Prop :=
  w ∈ PayoffProfileSet model ∧
    ¬ ∃ v : Profile model,
      v ∈ PayoffProfileSet model ∧ (∀ ω : model.Ω, w ω < v ω)

def WP : Set (Profile model) :=
  { w | WeakParetoProfile model w }

abbrev WPProfile : Type :=
  { w : Profile model // w ∈ WP model }

/-- The Bayes cone at a payoff profile `w`: the set of beliefs `μ` under which
`w` maximizes the expected payoff against all feasible profiles. -/
def BayesConeW (w : Profile model) : Set (Belief model.Ω) :=
  { μ | w ∈ PayoffProfileSet model ∧
      ∀ v : Profile model,
        v ∈ PayoffProfileSet model →
          beliefDot μ v ≤ beliefDot μ w }

/-- Normal-cone predicate (placeholder support function form). -/
def NormalConeW (w n : Profile model) : Prop :=
  w ∈ PayoffProfileSet model ∧
    ∀ v : Profile model,
      v ∈ PayoffProfileSet model →
        (∑ ω : model.Ω, n ω * (v ω - w ω)) ≤ 0

/-- Support function of a Bayes cone (or any belief set) against a payoff
profile `y`. -/
noncomputable def supportFunction
    (B : Set (Belief model.Ω)) (y : Profile model) : ℝ :=
  sSup ((fun μ : Belief model.Ω => beliefDot μ y) '' B)

/-- A bounded Borel-measurable family of payoff profiles indexed by messages.
This is the function-space over which the Hall dual quantifies (NOT bounded
continuous; the dual prices are Borel). -/
structure BoundedBorelProfile where
  toFun : model.M → Profile model
  measurable_toFun : Measurable toFun
  bounded_coord : ∃ C : ℝ, 0 ≤ C ∧ ∀ m ω, |toFun m ω| ≤ C

/-- Definition-2 q-a.e. robust rationalizability, lifted to v9 vocabulary by
recycling the v8 predicate. Uses `AgentStrategyFull` per v8's
`Definition2QAEPredicate` signature. -/
def RobustRationalizableQAE
    (pd : PosteriorDisintegration model)
    (β : AdviserKernel model)
    (σ : AgentStrategyFull model) : Prop :=
  Definition2QAEPredicate model pd β σ

/-- Existence form: there is some adversary β and agent strategy σ that are
q-a.e. robustly rationalizable under the disintegration `pd`. -/
def HasRobustRationalizableStrategy
    (pd : PosteriorDisintegration model) : Prop :=
  ∃ β : AdviserKernel model, ∃ σ : AgentStrategyFull model,
    RobustRationalizableQAE model pd β σ

/-! ### Finite-menu data for T1 -/

/-- Bundle of finite-menu data feeding the T1 Clarke–Danskin chain.
Most fields are `Prop` placeholders for per-lemma refinement. -/
structure FiniteMenuData (k : Nat) where
  w : Fin k → Profile model
  inWP : ∀ i, w i ∈ WP model
  localMax : Prop
  paretoCompleted : Prop
  lamPlus : model.M → Fin k → ℝ
  lamMinus : model.M → Fin k → ℝ
  g : Fin k → Profile model
  q : Fin k → ℝ
  clarkeDanskinRepresentation : Prop
  clarkeFermatStationarity : Prop
  multipliersAreCalibrationKernel : Prop
  multiplierBayesCone : Prop

/-! ### T2 data -/

structure AlphaZeroSingletonData where
  priorStrategy : AgentStrategyM model
  constantAdversary : AdviserKernel model
  priorOptimal : Prop
  posteriorAtConstantMessageIsPrior : Prop
  robustRationalizable : Prop

/-! ### Binary capstone data -/

structure BinaryCapstoneData where
  pd : PosteriorDisintegration model
  binaryStates : Fintype.card model.Ω = 2
  alpha_pos : 0 < model.α
  alpha_lt_one : model.α < 1
  L : Belief model.Ω
  R : Belief model.Ω
  endpointExposure : Prop
  tieDiscipline : Prop
  interiorEndpointStationarity : Prop
  endpointFiberLift : Prop
  trsIntervalReduction : Prop
  endpointOnlyImage : Prop
  interiorMessageCalibration : Prop
  endpointStationarityTotalBalance : Prop
  capstoneConclusion : HasRobustRationalizableStrategy model pd

/-! ### FBNF foliation and package -/

structure Foliation where
  Z : Type
  measurableZ : MeasurableSpace Z
  standardBorelZ : Prop
  a : Z → ℝ
  b : Z → ℝ
  intervalNonempty : ∀ z, a z ≤ b z
  ell : (z : Z) → {t : ℝ // a z ≤ t ∧ t ≤ b z} → Belief model.Ω
  affineFibers : Prop
  chartMeasurable : Prop
  disintegration : Prop
  quotientConsistent : Prop

structure FBNFPackage where
  pd : PosteriorDisintegration model
  card_ge_three : 3 ≤ Fintype.card model.Ω
  alpha_pos : 0 < model.α
  alpha_lt_one : model.α < 1
  foliation : Foliation model
  fiberPreservingTRS : Prop
  endpointSupportedFiberImage : Prop
  fiberEndpointExposure : Prop
  fiberTieDiscipline : Prop
  localTwoSidedPerturbability : Prop
  globalFiberDominance : Prop
  conditionalB1Pasting : Prop
  localizedStationarityFBNF6 : Prop
  capstoneConclusion : HasRobustRationalizableStrategy model pd

/-! ### Regularity package and Hall dual -/

structure RegPackage where
  pd : PosteriorDisintegration model
  wstar : model.M → Profile model
  wstar_inWP : ∀ m, wstar m ∈ WP model
  wstar_measurable : Measurable wstar
  G : model.M → Set model.M
  B : model.M → Set (Belief model.Ω)
  G_nonempty : ∀ s, (G s).Nonempty
  G_compact : ∀ s, IsCompact (G s)
  G_closedGraph : IsClosed {p : model.M × model.M | p.2 ∈ G p.1}
  B_closed : ∀ m, IsClosed (B m)
  -- Convexity of `B m` requires lifting beliefs out of the simplex subtype;
  -- placeholder Prop until the per-lemma prover round refines this.
  B_convex : Prop
  B_support_continuous :
    ∀ y : Profile model, Continuous fun m => supportFunction model (B m) y
  Psi : BoundedBorelProfile model → ℝ
  calibratedKernelExists : Prop
  robustRationalizableLabeling : Prop

def PsiNonpos (reg : RegPackage model) : Prop :=
  ∀ y : BoundedBorelProfile model, reg.Psi y ≤ 0

structure FiniteConeHallInstance where
  flowFeasible : Prop
  psiNonpos : Prop

structure WTAData where
  psiValue : ℝ
  certificatePositive : Prop
  reopeningThreshold : ℝ → Prop

structure PolyhedralLPInstance where
  finiteFacetHyp : Prop
  psiNonpos : Prop
  lpFeasible : Prop

structure P2StarHyp where
  reg : RegPackage model
  coneMargin : Prop
  boundedJamming : Prop
  enoughAlignedBaseline : Prop

structure P3Hyp where
  reg : RegPackage model
  polyhedralW : Prop
  finiteVertexMenu : Prop
  positiveConeMargin : Prop
  finiteLPFeasible : Prop

structure P4Hyp where
  reg : RegPackage model
  radialTau : Prop
  utilityEquivariant : Prop
  antipodalKernelConstructed : Prop
  scalarRadialBalance : Prop

structure BinaryTieSplittingHyp where
  data : BinaryCapstoneData model
  tieAtom : Prop
  measurableTieSplit : Prop

structure VariableMarginP2Hyp where
  reg : RegPackage model
  eta : model.M → ℝ
  eta_positive : ∀ᵐ m ∂model.τM, 0 < eta m
  localDensityCap : Prop
  variableConeMargin : Prop

structure GraphFBNFPackage where
  pd : PosteriorDisintegration model
  finiteGraph : Prop
  affineArcCharts : Prop
  endpointFiberTransportOnEdges : Prop
  kirchhoffNodeBalance : Prop
  crossEdgeDominance : Prop
  capstoneConclusion : HasRobustRationalizableStrategy model pd

end -- noncomputable section

/-! ## §3 Theorem T1 + sub-lemmas L6/L7/L8 -/

theorem «T1-L6-integral-clarke-danskin-representation»
    {model : RobustTrustModel} {k : Nat}
    (data : FiniteMenuData model k)
    (_hLocal : data.localMax)
    (_hPareto : data.paretoCompleted) :
    data.clarkeDanskinRepresentation := by
  sorry

theorem «T1-L7-clarke-fermat-stationarity»
    {model : RobustTrustModel} {k : Nat}
    (data : FiniteMenuData model k)
    (_h6 : data.clarkeDanskinRepresentation)
    (_hLocal : data.localMax)
    (_hPareto : data.paretoCompleted) :
    data.clarkeFermatStationarity := by
  sorry

theorem «T1-L8-multipliers-are-calibration-kernel»
    {model : RobustTrustModel} {k : Nat}
    (data : FiniteMenuData model k)
    (_h6 : data.clarkeDanskinRepresentation)
    (_h7 : data.clarkeFermatStationarity) :
    data.multipliersAreCalibrationKernel := by
  sorry

theorem «T1-clarke-danskin-multiplier-bayes-cone»
    {model : RobustTrustModel} {k : Nat}
    (data : FiniteMenuData model k)
    (_h6 : data.clarkeDanskinRepresentation)
    (_h7 : data.clarkeFermatStationarity)
    (_h8 : data.multipliersAreCalibrationKernel) :
    data.multiplierBayesCone := by
  sorry

/-! ## §4 Theorem T2 — α=0 unconditional singleton -/

theorem «T2-alpha-zero-singleton-prior-strategy»
    {model : RobustTrustModel}
    (pd : PosteriorDisintegration model)
    (_hα : model.α = 0)
    (data : AlphaZeroSingletonData model)
    (_hPrior : data.priorOptimal)
    (_hPost : data.posteriorAtConstantMessageIsPrior) :
    HasRobustRationalizableStrategy model pd := by
  sorry

/-! ## §5 Binary capstone L_B1 … L_B6 -/

theorem «binary-L_B1-endpoint-fiber-lift»
    {model : RobustTrustModel}
    (data : BinaryCapstoneData model)
    (_hBalance : data.endpointStationarityTotalBalance) :
    data.endpointFiberLift := by
  sorry

theorem «binary-L_B2-TRS-interval-reduction»
    {model : RobustTrustModel}
    (data : BinaryCapstoneData model) :
    data.trsIntervalReduction := by
  sorry

theorem «binary-L_B3-endpoint-only-image»
    {model : RobustTrustModel}
    (data : BinaryCapstoneData model)
    (_hTRS : data.trsIntervalReduction) :
    data.endpointOnlyImage := by
  sorry

theorem «binary-L_B4-interior-message-calibration»
    {model : RobustTrustModel}
    (data : BinaryCapstoneData model)
    (_hTRS : data.trsIntervalReduction)
    (_hEndpoint : data.endpointOnlyImage) :
    data.interiorMessageCalibration := by
  sorry

theorem «binary-L_B5-endpoint-stationarity-total-balance»
    {model : RobustTrustModel}
    (data : BinaryCapstoneData model)
    (_hT1 : ∀ k (fd : FiniteMenuData model k), fd.multiplierBayesCone)
    (_hTRS : data.trsIntervalReduction)
    (_hEndpoint : data.endpointOnlyImage)
    (_hIES : data.interiorEndpointStationarity) :
    data.endpointStationarityTotalBalance := by
  sorry

theorem «binary-L_B6-capstone»
    {model : RobustTrustModel}
    (data : BinaryCapstoneData model)
    (_hB1 : data.endpointFiberLift)
    (_hB2 : data.trsIntervalReduction)
    (_hB3 : data.endpointOnlyImage)
    (_hB4 : data.interiorMessageCalibration)
    (_hB5 : data.endpointStationarityTotalBalance) :
    HasRobustRationalizableStrategy model data.pd := by
  sorry

/-! ## §6 FBNF F1 … F4 + 3 corollaries -/

theorem «FBNF-F1-conditional-B1-measurable-pasting»
    {model : RobustTrustModel}
    (pkg : FBNFPackage model)
    (_hB1 : ∀ data : BinaryCapstoneData model,
      data.endpointStationarityTotalBalance → data.endpointFiberLift) :
    pkg.conditionalB1Pasting := by
  sorry

theorem «FBNF-F2-endpoint-only-fiber-image»
    {model : RobustTrustModel}
    (pkg : FBNFPackage model)
    (_hTRS : pkg.fiberPreservingTRS) :
    pkg.endpointSupportedFiberImage := by
  sorry

theorem «FBNF-F3-localized-stationarity-FBNF6»
    {model : RobustTrustModel}
    (pkg : FBNFPackage model)
    (_hT1 : ∀ k (fd : FiniteMenuData model k), fd.multiplierBayesCone)
    (_hF2 : pkg.endpointSupportedFiberImage)
    (_hPert : pkg.localTwoSidedPerturbability) :
    pkg.localizedStationarityFBNF6 := by
  sorry

theorem «FBNF-F4-capstone»
    {model : RobustTrustModel}
    (pkg : FBNFPackage model)
    (_hF1 : pkg.conditionalB1Pasting)
    (_hF2 : pkg.endpointSupportedFiberImage)
    (_hF3 : pkg.localizedStationarityFBNF6)
    (_hDom : pkg.globalFiberDominance) :
    HasRobustRationalizableStrategy model pkg.pd := by
  sorry

theorem «FBNF-corollary-spherical-radial»
    {model : RobustTrustModel}
    (pkg : FBNFPackage model)
    (_radial : P4Hyp model)
    (hF4 : HasRobustRationalizableStrategy model pkg.pd) :
    HasRobustRationalizableStrategy model pkg.pd :=
  hF4

theorem «FBNF-corollary-affine-MLR-single-crossing»
    {model : RobustTrustModel}
    (pkg : FBNFPackage model)
    (affineMLR : Prop)
    (singleCrossing : Prop)
    (hMLR_implies_FBNF :
      affineMLR → singleCrossing → HasRobustRationalizableStrategy model pkg.pd)
    (h1 : affineMLR) (h2 : singleCrossing) :
    HasRobustRationalizableStrategy model pkg.pd :=
  hMLR_implies_FBNF h1 h2

theorem «FBNF-corollary-polyhedral-scalarizable»
    {model : RobustTrustModel}
    (pkg : FBNFPackage model)
    (polyScalar : Prop)
    (hPolyScalar : polyScalar → HasRobustRationalizableStrategy model pkg.pd)
    (h : polyScalar) :
    HasRobustRationalizableStrategy model pkg.pd :=
  hPolyScalar h

/-! ## §7 Hall biconditional G1, G2c, Hall, WTA Ψ=2/9, WTA threshold D -/

theorem «Hall-G1-finite-cone-hall-farkas-LP»
    (inst : FiniteConeHallInstance) :
    inst.flowFeasible ↔ inst.psiNonpos := by
  sorry

theorem «Hall-G2c-borel-extension»
    {model : RobustTrustModel}
    (reg : RegPackage model)
    (_hPsi : PsiNonpos model reg) :
    reg.calibratedKernelExists := by
  sorry

theorem «Hall-biconditional»
    {model : RobustTrustModel}
    (reg : RegPackage model) :
    reg.robustRationalizableLabeling ↔ PsiNonpos model reg := by
  sorry

theorem «Hall-WTA-dual-certificate-psi-two-ninths»
    (wta : WTAData)
    (_hCert : wta.certificatePositive) :
    wta.psiValue = (2 : ℝ) / 9 := by
  sorry

/-- WTA reopening threshold. Follows the user-locked normalization
`D ≥ 2(1−α)/(9α)` per `source_proof.md` and `lean_state.md`; a competing
normalization `D ≥ 9α/(2(1−α))` flagged in `v9_consolidated.md` is being
adjudicated in the decomposition reviewer pass. -/
theorem «Hall-WTA-reopening-threshold-D»
    (α D : ℝ) (hα_pos : 0 < α) (_hα_lt : α < 1) :
    ((-2 * α * D + (1 - α) * ((4 : ℝ) / 9) ≤ 0)
      ↔ ((2 * (1 - α)) / (9 * α) ≤ D)) := by
  have h9α : (0 : ℝ) < 9 * α := by positivity
  rw [div_le_iff₀ h9α]
  constructor
  · intro h; nlinarith
  · intro h; nlinarith

/-! ## §8 G4 finite-facet polyhedral LP threshold -/

theorem «G4-finite-facet-polyhedral-LP-threshold»
    (inst : PolyhedralLPInstance) :
    inst.psiNonpos ↔ inst.lpFeasible := by
  sorry

/-! ## §9 Primitive sufficient classes P2*, P3, P4 -/

theorem «P2-star-cone-margin-bounded-jamming»
    {model : RobustTrustModel}
    (hyp : P2StarHyp model)
    (_hMargin : hyp.coneMargin)
    (_hJam : hyp.boundedJamming)
    (_hBase : hyp.enoughAlignedBaseline) :
    HasRobustRationalizableStrategy model hyp.reg.pd := by
  sorry

theorem «P3-polyhedral-cone-margin»
    {model : RobustTrustModel}
    (hyp : P3Hyp model)
    (_hPoly : hyp.polyhedralW)
    (_hFinite : hyp.finiteVertexMenu)
    (_hMargin : hyp.positiveConeMargin)
    (_hLP : hyp.finiteLPFeasible) :
    HasRobustRationalizableStrategy model hyp.reg.pd := by
  sorry

theorem «P4-radial-antipodal-tau-symmetry»
    {model : RobustTrustModel}
    (hyp : P4Hyp model)
    (_hRadial : hyp.radialTau)
    (_hEq : hyp.utilityEquivariant)
    (_hKernel : hyp.antipodalKernelConstructed)
    (_hBalance : hyp.scalarRadialBalance) :
    HasRobustRationalizableStrategy model hyp.reg.pd := by
  sorry

/-! ## §10 Section G v9.2 sharpenings -/

theorem «G-addendum-binary-tie-splitting»
    {model : RobustTrustModel}
    (hyp : BinaryTieSplittingHyp model)
    (_hTie : hyp.tieAtom)
    (_hSplit : hyp.measurableTieSplit) :
    hyp.data.endpointFiberLift := by
  sorry

theorem «G-addendum-variable-margin-P2-star-prime»
    {model : RobustTrustModel}
    (hyp : VariableMarginP2Hyp model)
    (_hEta : ∀ᵐ m ∂model.τM, 0 < hyp.eta m)
    (_hCap : hyp.localDensityCap)
    (_hCone : hyp.variableConeMargin) :
    HasRobustRationalizableStrategy model hyp.reg.pd := by
  sorry

theorem «G-addendum-P6_G-finite-graph-FBNF»
    {model : RobustTrustModel}
    (pkg : GraphFBNFPackage model)
    (_hGraph : pkg.finiteGraph)
    (_hArcs : pkg.affineArcCharts)
    (_hEdge : pkg.endpointFiberTransportOnEdges)
    (_hKirchhoff : pkg.kirchhoffNodeBalance)
    (_hDom : pkg.crossEdgeDominance) :
    HasRobustRationalizableStrategy model pkg.pd := by
  sorry

end RobustTrustV9
